services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${PROD_DATABASE_USERNAME}'
      - 'POSTGRES_PASSWORD=${PROD_DATABASE_PASSWORD}'
      - 'POSTGRES_USER=${PROD_DATABASE_NAME}'
    ports:
      - '${PROD_DATABASE_PORT}:5432'
